# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852283ebff61dcd438739c08d6fc710b506cc263a49785252a85ac765490863a29876ff1ef116f4b06e75b6893c7255a0826737843302b963f6462820e0933ec

test:
  secret_key_base: 446352ed0f86d56e830391815f6cd460f77ec22e337c17eec78e8fa1763d509533493515382e19655558edefbd178c4cbb59daa8182e51e99403b31664c26d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
